server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # React Router — siempre devuelve index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy inverso hacia los microservicios
    location /api/usuarios/ {
        proxy_pass http://ms-usuarios:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/reportes/ {
        proxy_pass http://ms-reportes:8082/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/monitoreo/ {
        proxy_pass http://ms-monitoreo:8083/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/alertas/ {
        proxy_pass http://ms-alertas:8084/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
