# Configuración de la Base de Datos H2 en Memoria
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar la Consola de H2
spring.h2.console.enabled=true

# Opcional: Para que JPA cree las tablas automáticamente a partir de tus entidades
spring.jpa.hibernate.ddl-auto=update

# Desactivar la inicialización de la base de datos por scripts (data.sql, schema.sql)
# ya que estamos usando un CommandLineRunner para poblar los datos.
spring.sql.init.mode=never
