spring.application.name=ms-monitoreo

# El puerto interno del contenedor
server.port=8080

# Las URLs de los clientes Feign se inyectan desde docker-compose.yml

# Desactiva Eureka en este perfil
eureka.client.enabled=false

# ms-monitoreo no tiene BD propia, desactivar autoconfig de DataSource
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
