spring.application.name=ms-monitoreo
server.port=8083

# -- MySQL: database per service --
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/sifire_monitoreo?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

eureka.client.enabled=false
spring.cloud.discovery.enabled=false

# URLs Feign clients
ms.alertas.url=${MS_ALERTAS_URL:http://localhost:8084}
ms.reportes.url=${MS_REPORTES_URL:http://localhost:8082}
ms.usuarios.url=${MS_USUARIOS_URL:http://localhost:8081}

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true