spring.application.name=ms-monitoreo

# El puerto interno del contenedor
server.port=8080

# Las URLs de los clientes Feign se inyectarán desde docker-compose.yml

# Desactiva Eureka en este perfil
eureka.client.enabled=false
