spring.application.name=ms-usuarios
<<<<<<< HEAD
server.port=8081

# --- Configuración de la Base de Datos H2 en Memoria ---
spring.datasource.url=jdbc:h2:mem:usuariosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
=======
server.port=8080

# La configuracion de la base de datos (URL, user, pass) se inyecta desde docker-compose.yml
>>>>>>> 0b24b7cbe439910071b62b1306c0d243655ca1b8

# --- Configuración de JPA y Hibernate ---
# Dialecto para H2 (ESTA ES LA CORRECCIÓN)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# --- Consola H2 ---
spring.h2.console.enabled=true

# --- Desactiva Eureka en este perfil ---
eureka.client.enabled=false
