spring.application.name=ms-reportes

# El puerto interno del contenedor
server.port=8080

# La configuración de la base de datos (URL, user, pass) se inyectará desde docker-compose.yml
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Desactiva Eureka en este perfil
eureka.client.enabled=false
