spring.application.name=ms-alertas
server.port=8080

# La configuracion de la base de datos se inyecta desde docker-compose.yml
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Desactiva Eureka
eureka.client.enabled=false
