spring.application.name=ms-alertas

# --- Puerto del Servidor ---
server.port=8082

# --- Configuración de la Base de Datos H2 en Memoria ---
spring.datasource.url=jdbc:h2:mem:alertasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- Configuración de JPA y Hibernate ---
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# --- Consola H2 ---
# Permite acceder a la base de datos en memoria desde el navegador
# URL: http://localhost:8082/h2-console
# JDBC URL: jdbc:h2:mem:alertasdb
spring.h2.console.enabled=true

# --- Configuración de Eureka ---
# Evita que el microservicio intente registrarse en Eureka durante el desarrollo local
eureka.client.enabled=false

# --- Configuración de Clientes Feign ---
ms-usuarios.url=http://localhost:8081
