spring.application.name=ms-alertas
server.port=8080

# La configuracion de la base de datos (URL, user, pass) se inyecta desde docker-compose.yml
# La URL del cliente Feign (ms-usuarios.url) se inyecta desde docker-compose.yml

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Desactiva Eureka en este perfil
eureka.client.enabled=false
