spring.application.name=ms-bff
server.port=8080

# -- URLs de microservicios (sin Docker, modo local) --
ms.usuarios.url=http://localhost:8081
ms.reportes.url=http://localhost:8082
ms.monitoreo.url=http://localhost:8083
ms.alertas.url=http://localhost:8084

eureka.client.enabled=false
spring.cloud.discovery.enabled=false

# -- Resilience4j Circuit Breaker --
resilience4j.circuitbreaker.instances.ms-usuarios.sliding-window-size=5
resilience4j.circuitbreaker.instances.ms-usuarios.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.ms-usuarios.wait-duration-in-open-state=10s

resilience4j.circuitbreaker.instances.ms-reportes.sliding-window-size=5
resilience4j.circuitbreaker.instances.ms-reportes.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.ms-reportes.wait-duration-in-open-state=10s

resilience4j.circuitbreaker.instances.ms-alertas.sliding-window-size=5
resilience4j.circuitbreaker.instances.ms-alertas.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.ms-alertas.wait-duration-in-open-state=10s

resilience4j.circuitbreaker.instances.ms-monitoreo.sliding-window-size=5
resilience4j.circuitbreaker.instances.ms-monitoreo.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.ms-monitoreo.wait-duration-in-open-state=10s

# -- Actuator --
management.endpoints.web.exposure.include=health,circuitbreakers
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true
