version: '3.8'

services:
  # --- Contenedor de la Base de Datos MySQL (Compartido) ---
  db-alertas:
    image: mysql:8.0
    container_name: db-alertas
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: sifire_alertas
    ports:
      - "3307:3306"
    volumes:
      - mysql_alertas_data:/var/lib/mysql
    networks:
      - sifire-network
    command: --default-authentication-plugin=mysql_native_password

  # --- Microservicio de Alertas ---
  ms-alertas:
    image: ms-alertas:latest
    container_name: ms-alertas
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-alertas:3306/sifire_alertas?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword123
      - MS-USUARIOS_RIBBON_LISTOFSERVERS=http://ms-usuarios:8081
    depends_on:
      - db-alertas
    networks:
      - sifire-network

  # --- Microservicio de Monitoreo ---
  ms-monitoreo:
    build:
      context: ./ms-monitoreo
    container_name: ms-monitoreo
    ports:
      - "8082:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-alertas:3306/sifire_monitoreo?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword123
    depends_on:
      - db-alertas
    networks:
      - sifire-network

  # --- Microservicio de Usuarios ---
  ms-usuarios:
    build:
      context: ./ms-usuarios
    container_name: ms-usuarios
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-alertas:3306/sifire_usuarios?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword123
    depends_on:
      - db-alertas
    networks:
      - sifire-network

  # --- Nuevo Microservicio: Reportes ---
  ms-reportes:
    build:
      context: ./ms-reportes  # Docker buscará el Dockerfile en la carpeta ms-reportes
    container_name: ms-reportes
    ports:
      - "8083:8082" # Expone el puerto 8083 para Reportes
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-alertas:3306/sifire_reportes?useSSL=false&serverTimezone=America/Santiago&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=rootpassword123
    depends_on:
      - db-alertas
    networks:
      - sifire-network

networks:
  sifire-network:
    driver: bridge

volumes:
  mysql_alertas_data: